### ISSUE TITLE
StorageOS 2 and OKD 4.4 volumes created after installation not visible in dashboard and not spread across nodes

### ISSUE THREAD

**Issue by PiotrKlimczak** [storageos/cluster-operator#238]
StorageOS 2 and OKD 4.4 volumes created after installation not visible in dashboard and not spread across nodes.
So when I create 2 replica volume, I can see on compute node that all replicas has been in fact created on single compute node.
This however works correctly when volume is created from dashboard.
Tested on bare metal OKD 4.4 Beta3 installation with 3 masters and 3 compute nodes.

**Comment by Arau** [comment]
Question already answered on slack.

**Comment by Arau** [comment]
Even though most of the questions have been addressed through the Slack channel, we would like to add information to the issue. 

The StorageOS GUI segments the Volumes following the Kubernetes namespaces or in this case the OpenShift projects where the PVC is placed. In the GUI, there is picker selector at the top left to choose what namespace is the current view of the Volumes page. See the image attached. 
<img width="1415" alt="Screen Shot 2020-04-22 at 11 22 25" src="https://user-images.githubusercontent.com/1422556/79971102-c776e580-848b-11ea-9353-9db12503c13e.png">

Regarding the replicas, StorageOS has a placement algorithm that doesn't allow the master and its replicas to be in the same instance. A volume with 2 replicas requires 3 nodes, one for the master and one for each replica. Otherwise, if that requirement is not met, the volume provisioning will fail. 

I would recommend using the dynamic provisioning functionality that StorageOS provides by provisioning PVCs. When a PVC is provisioned, StorageOS provisions a Volume and maps it with a PV. Creating a Volume from the GUI does not create a PVC or PV. That procedure is manual. Therefore we would recommend to use a PVC and let the automation work for you.
