### ISSUE TITLE
When trying to deploy, gcr.io/google-containers/kube-scheduler:v1.18.8 is not found and install can';t complete

### ISSUE THREAD

**Issue by birdiesanders** [storageos/cluster-operator#272]
It seems that this image is not in the registry.

**Comment by birdiesanders** [comment]
It seems that there is simply no skube-scheduler container image on grc-io, I am unsure of how I should proceed from here.

**Comment by Arau** [comment]
Hello @birdiesanders ,

The StorageOS Cluster Operator detects the version and distribution of Kubernetes and based on that, it sets the image for the scheduler, which is a Kubernetes official image. We are looking why this one is not accessible. 

In the meantime, you can follow the installation by disabling the scheduler. In the StorageOSCluster Custom Resource, you can define 

```
spec:
    disableScheduler: true
```

Of course it is better to have the scheduler extender installed because it influences the kubernetes scheduler to keep pods close to its data.

**Comment by Arau** [comment]
Hello @birdiesanders,

we have found that the latest release of Kubernetes didn't generate all the assets as usual. The repository where the kubescheduler official image changed. We are amending the references internally and checking the images for all previous versions for backwards compatibility. We will release a cluster image operator promptly.

**Comment by birdiesanders** [comment]
Great work on being speedy! Looks like you were able to fix it with a one-line change! If only everything were so simple.

**Comment by Arau** [comment]
Hi @birdiesanders, we have released a Cluster Operator Patch with a fix for it (v2.2.0).

Thank you for helping us with this issue. It is greatly appreciate it!
